spring.application.name=shms-backend

# MYSQL DATABASE CONFIGURATION

spring.datasource.url=jdbc:mysql://localhost:3306/shms

spring.datasource.username=root

spring.datasource.password=root1234

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HIBERNATE

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# SERVER PORT

server.port=8080